import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
// import SiteHeader from "@/components/site-header";
// import { ThemeProvider } from "@/components/theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Navbar from "@/components/Navbar/Navbar";
const inter = JetBrains_Mono({ subsets: ["latin"] });
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  const getDirection = (locale: string) => {
    const rtlLocals = ["ar"];
    return rtlLocals.includes(locale) ? "rtl" : "ltr";
  };
  const dataDir = getDirection(locale);

  console.log("locale:", locale);
  console.log("dir:", dataDir);

  return (
    <html lang={locale} dir={dataDir} suppressHydrationWarning>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > */}
          <Navbar />
          <div className="max-w-7xl mx-auto">{children}</div>
          {/* </ThemeProvider> */}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
